In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [6]:
df = pd.read_csv("emails.csv")

In [7]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [8]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [9]:
X=df.drop(['Email No.','Prediction'],axis=1)
Y=df['Prediction']
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)



In [11]:
print("Number of samples in 'text':", X_train.shape[0])
print("Number of samples in 'label':", y_train.shape[0])


Number of samples in 'text': 3620
Number of samples in 'label': 3620


In [12]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

In [13]:
y_pred_knn

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [14]:
print("KNN Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))


KNN Confusion Matrix:
 [[937 150]
 [ 67 398]]


In [15]:
print("KNN Classification Report:")
print(classification_report(y_test, y_pred_knn))

KNN Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.86      0.90      1087
           1       0.73      0.86      0.79       465

    accuracy                           0.86      1552
   macro avg       0.83      0.86      0.84      1552
weighted avg       0.87      0.86      0.86      1552



In [ ]:
svm = SVC(kernel='linear', probability=True)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

In [ ]:

print("SVM Classification Report:")
print(classification_report(y_test, y_pred_svm))

SVM Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1086
           1       0.92      0.92      0.92       466

    accuracy                           0.95      1552
   macro avg       0.94      0.94      0.94      1552
weighted avg       0.95      0.95      0.95      1552



In [ ]:
print("SVM Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

SVM Confusion Matrix:
 [[1049   37]
 [  37  429]]
